1721050383-NguyenThiHuyen/1721050383-NguyenThiHuyen/Models/MyProcess/Xuly.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _1721050383_NguyenThiHuyen.Models.MyProcess
{
    public class Xuly
    {
        int n, i;
        int dem = 0;
        string ketqua = "";
        ketqua = "nhap n bat ki: ";
            n = Convert.ToInt32(nhapn);
            for (i = 1; i <= n; i++)
                if (n % i == 0)
                    dem++;
            if (dem == 0)
                ketqua = ("số đã cho là số nguyên tố");
            else
                ketqua = ("số đã cho không là số nguyên tố");
    }
}

1721050383-NguyenThiHuyen/1721050383-NguyenThiHuyen/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _1721050383_NguyenThiHuyen.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

1721050383-NguyenThiHuyen/1721050383-NguyenThiHuyen/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _1721050383_NguyenThiHuyen.Controllers
{
    public class IndexController : Controller
    {
        // GET: Index
        public ActionResult Index(string Hoten, string ngaysinh)


        {
            ViewBag.thongbao = "chào mừng: " + Hoten;
            ViewBag.ngaysinh = ngaysinh;
            return View();
        }
    }
}

1721050383-NguyenThiHuyen/1721050383-NguyenThiHuyen/Controllers/phuongtrinhbac2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _1721050383_NguyenThiHuyen.Controllers
{
    public class phuongtrinhbac2Controller : Controller
    {
		// GET: phuongtrinhbac2
		public ActionResult phuongtrinhbac2(string hesoA, string hesoB, string hesoC)
		{
			Double a, b, c, delta, x1 = 0, x2 = 0;
			string Ketqua = "";
			a = Convert.ToDouble(hesoA);
			b = Convert.ToDouble(hesoB);
			c = Convert.ToDouble(hesoC);
			delta = b * b - 4 * a * c;
			if (delta > 0)
			{
				//Có hai nghiệm phân biệt
				x1 = (-b + Math.Sqrt(delta)) / (2 * a);
				x2 = (-b - Math.Sqrt(delta)) / (2 * a);
				Ketqua = ("Phương trình có hai nghiệm phân biệt:");
				Ketqua = ("x1 = " + x1 + ", x2 = " + x2);
			}
			else if (delta == 0)
			{
				//Có nghiệm kép
				x1 = x2 = -b / (2 * a);
				Ketqua = ("Phương trình có nghiệm kép:");
				Ketqua = ("x1 = x2 = " + x2);
			}
			else
				Ketqua = ("Phương trình vô nghiệm");
			ViewBag.thongbao = "ket qua của pt: " + Ketqua;
			return View();
		}
	}
}

1721050383-NguyenThiHuyen/1721050383-NguyenThiHuyen/Controllers/songuyentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _1721050383_NguyenThiHuyen.Controllers
{
    public class songuyentoController : Controller
    {
        // GET: songuyento
        public ActionResult songuyento(string nhapn)
        {
           int n,i;
            int dem = 0;
            string ketqua = "";
            ketqua = "nhap n bat ki: ";
            n = Convert.ToInt32(nhapn);
            for (i = 1; i <= n; i++)
                if (n % i == 0)
                    dem++;
            if (dem == 2)
                ketqua = ("số đã cho là số nguyên tố");
            else
                ketqua = ("số đã cho không là số nguyên tố");

            ViewBag.thongbao = "kết quả:" + ketqua;
            return View();
        }
    }
}

1721050383-NguyenThiHuyen/1721050383-NguyenThiHuyen/Controllers/tinhtongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _1721050383_NguyenThiHuyen.Controllers
{
    public class tinhtongController : Controller
    {
        // GET: tinhtong
            public ActionResult tinhtong(string nhapn)
            {
                int n;
                double s = 0;
                string ketqua = "";
                ketqua = "Tinh tong day so :";
                n = Convert.ToInt32(nhapn);
                for (double i = 1; i <= n; i++)
                {
                    s += 1 / i;
                }
                ViewBag.message = " tong cua day phan tu:" + s;
                return View();
            }
        }
    }

1721050383-NguyenThiHuyen/1721050383-NguyenThiHuyen/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

1721050383-NguyenThiHuyen/1721050383-NguyenThiHuyen/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

1721050383-NguyenThiHuyen/1721050383-NguyenThiHuyen/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

1721050383-NguyenThiHuyen/1721050383-NguyenThiHuyen/Views/Index/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<h1> HelloWorld</h1>
@using (Html.BeginForm())
{
    <label>Nhập Họ Tên</label>
    <input type="text" name="Hoten" />
    <label>nhập ngày sinh</label>
    <input type="date" name="ngaysinh" />
    <input type="submit" value="gửi Dữ liệu" />

}

1721050383-NguyenThiHuyen/1721050383-NguyenThiHuyen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("tính tổng", "tinhtong", "tinhtong")</li>
                    <li>@Html.ActionLink("giải pt bậc 2", "phuongtrinhbac2", "phuongtrinhbac2")</li>
                    <li>@Html.ActionLink("số nguyên tố", "songuyento", "songuyento")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

1721050383-NguyenThiHuyen/1721050383-NguyenThiHuyen/Views/phuongtrinhbac2/phuongtrinhbac2.cshtml
@{
    ViewBag.Title = "phuongtrinhbac2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>phuongtrinhbac2</h2>
@using (Html.BeginForm())
{
    <label> nhập a:</label>
    <input type="text" name="hesoA" />
    <label> Nhập b:</label>
    <input type="text" name="hesoB" />
    <lable> nhập c:</lable>
    <input type="text" name="hesoC" />
    <input type="submit" name="name" value="kết quả" />
}
@ViewBag.thongbao

1721050383-NguyenThiHuyen/1721050383-NguyenThiHuyen/Views/songuyento/songuyento.cshtml
@{
    ViewBag.Title = "songuyento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>songuyento</h2>
@using (Html.BeginForm())
{
    <label> Nhap n:</label>
    <input type="text" name="nhapn" />
    <input type="submit" value="kết quả" />
}
@ViewBag.thongbao

1721050383-NguyenThiHuyen/1721050383-NguyenThiHuyen/Views/tinhtong/tinhtong.cshtml
@{
    ViewBag.Title = "tinhtong";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>tinhtong</h2>
@{
    ViewBag.Title = "tinhtong";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>tinhtong</h2>
@using (Html.BeginForm())
{
    <label> Nhap n:</label>
    <input type="text" name="nhapn" />
    <input type="submit" value="kết quả" />
}
@ViewBag.message